/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FACTORIAL_H_RPCGEN
#define _FACTORIAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define factorial_PROG 0x23451111
#define factorial_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define factorial 1
extern  int * factorial_1(int *, CLIENT *);
extern  int * factorial_1_svc(int *, struct svc_req *);
extern int factorial_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define factorial 1
extern  int * factorial_1();
extern  int * factorial_1_svc();
extern int factorial_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FACTORIAL_H_RPCGEN */
