/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "palin.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
