/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "palin.h"

void palin_program_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	str plain_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, PALIN_PROGRAM, PALIN_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	printf("Enter the string: ");
	scanf("%[^\n]%*c", plain_1_arg.arr);
	result_1 = plain_1(&plain_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		if (*result_1 == 1)
		{
			printf("The string %s is palindrome\n", plain_1_arg.arr);
		}
		else
		{
			printf("The string %s is not palindrome\n", plain_1_arg.arr);
		}
	}
	printf("\n");
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	palin_program_1(host);
	exit(0);
}
