/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"

int *
prime_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int n=*argp;
	printf("prime(%d) is called\n",n);
	result=1;
	for(int i=2;i<=n/2;i++){
	if(n%i==0)
	{
	result=0;
	break;
	}
	}
	if(n==1)
	result=3;
	return &result;
}
