/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  calc_1_arg;
	char temp;
#ifndef	DEBUG
	clnt = clnt_create (host, calc_PROG, calc_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Enter 2 numbers: ");
	scanf("%d%d",&(calc_1_arg.a),&(calc_1_arg.b));
	scanf("%c",&temp);
	printf("Press a for addition, s for subtraction, m for multiplication, d for division and r for modulus: ");
	scanf("%c",&(calc_1_arg.op));
	result_1 = calc_1(&calc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
	printf("Result: %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host);
exit (0);
}
