/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIB_H_RPCGEN
#define _FIB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sequence {
	int a[100];
};
typedef struct sequence sequence;

#define FIB_PROG 0x23411000
#define FIB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define fib 1
extern  sequence * fib_1(int *, CLIENT *);
extern  sequence * fib_1_svc(int *, struct svc_req *);
extern int fib_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fib 1
extern  sequence * fib_1();
extern  sequence * fib_1_svc();
extern int fib_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sequence (XDR *, sequence*);

#else /* K&R C */
extern bool_t xdr_sequence ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIB_H_RPCGEN */
