/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gcd.h"

int *gcd_1_svc(two_num *argp, struct svc_req *rqstp)
{
	static int result;

	printf("GCD with numbers %d and %d was called\n", argp->a, argp->b);
	int temp;
	while (argp->a != 0)
	{
		temp = argp->a;
		argp->a = argp->b % argp->a;
		argp->b = temp;
	}
	result = argp->b;
	return &result;
}
