package ChatApplication;


/**
* ChatApplication/ModeratorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../ChatApplication.idl
* Thursday, 29 April, 2021 1:30:47 PM IST
*/

abstract public class ModeratorHelper
{
  private static String  _id = "IDL:ChatApplication/Moderator:1.0";

  public static void insert (org.omg.CORBA.Any a, ChatApplication.Moderator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ChatApplication.Moderator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ChatApplication.ModeratorHelper.id (), "Moderator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ChatApplication.Moderator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ModeratorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ChatApplication.Moderator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ChatApplication.Moderator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ChatApplication.Moderator)
      return (ChatApplication.Moderator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ChatApplication._ModeratorStub stub = new ChatApplication._ModeratorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ChatApplication.Moderator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ChatApplication.Moderator)
      return (ChatApplication.Moderator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ChatApplication._ModeratorStub stub = new ChatApplication._ModeratorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
