package ChatApplication;


/**
* ChatApplication/ModeratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../ChatApplication.idl
* Thursday, 29 April, 2021 1:30:47 PM IST
*/

public interface ModeratorOperations 
{
  String login (String username);
  String sendMessage (String username, String mssg);
  String getMessages ();
  String logout (String username);
} // interface ModeratorOperations
