package ChatApplication;

/**
* ChatApplication/ModeratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../ChatApplication.idl
* Thursday, 29 April, 2021 1:30:47 PM IST
*/

public final class ModeratorHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatApplication.Moderator value = null;

  public ModeratorHolder ()
  {
  }

  public ModeratorHolder (ChatApplication.Moderator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApplication.ModeratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApplication.ModeratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApplication.ModeratorHelper.type ();
  }

}
