package ChatApplication;


/**
* ChatApplication/Moderator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../ChatApplication.idl
* Thursday, 29 April, 2021 1:30:47 PM IST
*/

public interface Moderator extends ModeratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Moderator
