package ChatApplication;


/**
* ChatApplication/ModeratorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../ChatApplication.idl
* Thursday, 29 April, 2021 1:30:47 PM IST
*/

public abstract class ModeratorPOA extends org.omg.PortableServer.Servant
 implements ChatApplication.ModeratorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("sendMessage", new java.lang.Integer (1));
    _methods.put ("getMessages", new java.lang.Integer (2));
    _methods.put ("logout", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatApplication/Moderator/login
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.login (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ChatApplication/Moderator/sendMessage
       {
         String username = in.read_string ();
         String mssg = in.read_string ();
         String $result = null;
         $result = this.sendMessage (username, mssg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ChatApplication/Moderator/getMessages
       {
         String $result = null;
         $result = this.getMessages ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ChatApplication/Moderator/logout
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.logout (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatApplication/Moderator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Moderator _this() 
  {
    return ModeratorHelper.narrow(
    super._this_object());
  }

  public Moderator _this(org.omg.CORBA.ORB orb) 
  {
    return ModeratorHelper.narrow(
    super._this_object(orb));
  }


} // class ModeratorPOA
