/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "leap.h"

void leap_program_1(char *host)
{
	CLIENT *clnt;
	bool_t *result_1;
	int leap_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, LEAP_PROGRAM, LEAP_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	printf("Enter a year: ");
	scanf("%d", &leap_1_arg);
	result_1 = leap_1(&leap_1_arg, clnt);
	if (result_1 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		if (*result_1)
			printf("The year %d is a leap year\n", leap_1_arg);
		else
			printf("The year %d is not a leap year\n", leap_1_arg);
	}
	printf("\n");
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	leap_program_1(host);
	exit(0);
}
