/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LEAP_H_RPCGEN
#define _LEAP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LEAP_PROGRAM 0x23451111
#define LEAP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define leap 1
extern  bool_t * leap_1(int *, CLIENT *);
extern  bool_t * leap_1_svc(int *, struct svc_req *);
extern int leap_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leap 1
extern  bool_t * leap_1();
extern  bool_t * leap_1_svc();
extern int leap_program_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LEAP_H_RPCGEN */
