/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GCD_H_RPCGEN
#define _GCD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct two_num {
	int a;
	int b;
};
typedef struct two_num two_num;

#define GCD_PROGRAM 0x23451111
#define GCD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define gcd 1
extern  int * gcd_1(two_num *, CLIENT *);
extern  int * gcd_1_svc(two_num *, struct svc_req *);
extern int gcd_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define gcd 1
extern  int * gcd_1();
extern  int * gcd_1_svc();
extern int gcd_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_two_num (XDR *, two_num*);

#else /* K&R C */
extern bool_t xdr_two_num ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GCD_H_RPCGEN */
