/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gcd.h"

void gcd_program_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	two_num gcd_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, GCD_PROGRAM, GCD_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	printf("Enter two numbers: ");
	scanf("%d %d", &gcd_1_arg.a, &gcd_1_arg.b);
	result_1 = gcd_1(&gcd_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("GCD of the numbers %d and %d is %d\n", gcd_1_arg.a, gcd_1_arg.b, *result_1);
	}
	printf("\n");
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	gcd_program_1(host);
	exit(0);
}
