# DO NOT EDIT THIS FILE!
#
# Python module ChatApplication__POA generated by omniidl

import omniORB
omniORB.updateModule("ChatApplication__POA")

# ** 1. Stub files contributing to this module
import ChatApplication_idl

# ** 2. Sub-modules

# ** 3. End
